version: '3.8'
services:
  webhook-server:
    build: .
    ports:
      - '3001:3001'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ['yarn', 'dev']
